const number_all_prompts = 113;
const all_prompts = [
    "Chest pain",
    "Being late to school",
    "Being tired in the morning",
    "Stop people from doomscrolling without banning phones",
    "Make airport security actually enjoyable",
    "Get people to drink more water",
    "Eliminate traffic without building roads",
    "Make homework fun",
    "Replace alarm clocks",
    "Reduce food waste at buffets",
    "Invent a better umbrella",
    "Make public speaking painless",
    "Get strangers to trust each other faster",
    "End spam calls forever",
    "Make meetings 50% shorter",
    "Stop socks from disappearing",
    "Create a business that makes waiting in line exciting",
    "Fix online dating",
    "Help people remember names",
    "Make exercise addictive (in a good way)",
    "Solve package theft",
    "Replace passwords",
    "Make healthy food feel like junk food",
    "Get everyone to recycle properly",
    "Make long flights enjoyable",
    "Fix customer service hold music",
    "Help people wake up energized",
    "Create a way to share dreams",
    "Stop procrastination",
    "Reduce exam stress",
    "Make houseplants impossible to kill",
    "Fix group projects",
    "Make networking not awkward",
    "Invent a business around awkward silence",
    "Make parking effortless",
    "End email overload",
    "Fix rainy-day commuting",
    "Create a better movie theater experience",
    "Make language learning instant-feeling",
    "Stop ice cream from melting",
    "Help people make friends as adults",
    "Solve concert ticket scalping",
    "Replace business cards",
    "Fix lost luggage",
    "Make public transit entertaining",
    "Help people read more books",
    "Create a better tip system",
    "Solve people ghosting each other",
    "Reduce screen time",
    "Make grocery shopping faster",
    "End tangled cables",
    "Help people keep New Year's resolutions",
    "Fix office temperature arguments",
    "Make chores feel like games",
    "Reduce food delivery costs",
    "Help people decide what to eat",
    "Create better birthday gifts",
    "Stop noisy neighbors",
    "Replace resumes",
    "Make hotel check-ins instant",
    "Invent a better backpack",
    "Fix pet separation anxiety",
    "Make cleaning satisfying",
    "Get people excited to vote",
    "Help students choose careers",
    "Fix awkward elevator rides",
    "Make museums more interactive",
    "Stop losing motivation halfway through goals",
    "Invent a better handshake",
    "Create a better gym experience",
    "Fix family group chats",
    "Make reusable bags impossible to forget",
    "Reduce road rage",
    "Help people stick to sleep schedules",
    "Make museums profitable",
    "Fix bad WiFi",
    "Help people remember where they parked",
    "Reduce returns in online shopping",
    "Invent a better shopping cart",
    "Make people enjoy taxes",
    "Fix awkward first dates",
    "Create a business around boredom",
    "Stop autocorrect disasters",
    "Help people stop biting nails",
    "Make commuting productive",
    "Fix bad roommates",
    "Create a better lunch break",
    "Make learning history exciting",
    "Replace tipping culture",
    "Solve boredom in waiting rooms",
    "Help people save money automatically",
    "Fix online reviews",
    "Make retirement planning fun",
    "Create a product for left-handed people",
    "Help people stop losing chargers",
    "Make weather forecasts feel personalized",
    "Fix cold pizza",
    "Make networking events enjoyable",
    "Create a better elevator",
    "Stop people from forgetting birthdays",
    "Help introverts meet people",
    "Invent a business around laziness",
    "Reduce shopping cart abandonment",
    "Make office chairs exciting",
    "Create a better queue system",
    "Fix awkward small talk",
    "Make public benches more useful",
    "Help people finish TV shows",
    "Replace CAPTCHA",
    "Fix people forgetting passwords",
    "Create a business around nostalgia",
    "Make taking medicine enjoyable",
    "Help people stop hitting snooze"
];

module.exports = { 
    number_all_prompts,
    all_prompts 
};

// project is done with require, not import, so use this instead of export -> then require them in order